export default function useQuotation() {
  const titleTxt = {
    txt1: 'ORDER',
    txt2: 'PLACEMENT',
    txt3: 'PROCESS',
  }

  const Categories = ['Everyday', 'Formal', 'Performance', 'Medical Compression', 'Baby']

  const everydayList = [
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'No Show',
      Materials: 'Cotton',
      pricePerPair: 0.42,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'No Show',
      Materials: 'Cotton',
      pricePerPair: 0.45,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'No Show',
      Materials: 'Cotton',
      pricePerPair: 0.48,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'No Show',
      Materials: 'Cotton',
      pricePerPair: 0.51,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'Low Cut',
      Materials: 'Cotton',
      pricePerPair: 0.46,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'Low Cut',
      Materials: 'Cotton',
      pricePerPair: 0.49,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'Low Cut',
      Materials: 'Cotton',
      pricePerPair: 0.52,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'Low Cut',
      Materials: 'Cotton',
      pricePerPair: 0.55,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'Quarter ',
      Materials: 'Cotton',
      pricePerPair: 0.49,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'Quarter ',
      Materials: 'Cotton',
      pricePerPair: 0.52,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'Quarter ',
      Materials: 'Cotton',
      pricePerPair: 0.55,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'Quarter ',
      Materials: 'Cotton',
      pricePerPair: 0.58,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'Crew',
      Materials: 'Cotton',
      pricePerPair: 0.56,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'Crew',
      Materials: 'Cotton',
      pricePerPair: 0.61,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'Crew',
      Materials: 'Cotton',
      pricePerPair: 0.66,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'Crew',
      Materials: 'Cotton',
      pricePerPair: 0.71,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'No Show',
      Materials: 'Polyester',
      pricePerPair: 0.36,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'No Show',
      Materials: 'Polyester',
      pricePerPair: 0.39,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'No Show',
      Materials: 'Polyester',
      pricePerPair: 0.42,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'No Show',
      Materials: 'Polyester',
      pricePerPair: 0.45,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'Low Cut',
      Materials: 'Polyester',
      pricePerPair: 0.4,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'Low Cut',
      Materials: 'Polyester',
      pricePerPair: 0.43,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'Low Cut',
      Materials: 'Polyester',
      pricePerPair: 0.46,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'Low Cut',
      Materials: 'Polyester',
      pricePerPair: 0.49,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'Quarter ',
      Materials: 'Polyester',
      pricePerPair: 0.43,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'Quarter ',
      Materials: 'Polyester',
      pricePerPair: 0.46,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'Quarter ',
      Materials: 'Polyester',
      pricePerPair: 0.49,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'Quarter ',
      Materials: 'Polyester',
      pricePerPair: 0.52,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'Crew',
      Materials: 'Polyester',
      pricePerPair: 0.49,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'Crew',
      Materials: 'Polyester',
      pricePerPair: 0.53,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'Crew',
      Materials: 'Polyester',
      pricePerPair: 0.57,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'Crew',
      Materials: 'Polyester',
      pricePerPair: 0.61,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'No Show',
      Materials: 'Wool',
      pricePerPair: 1.4,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'No Show',
      Materials: 'Wool',
      pricePerPair: 1.6,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'No Show',
      Materials: 'Wool',
      pricePerPair: 1.8,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'No Show',
      Materials: 'Wool',
      pricePerPair: 2,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'Low Cut',
      Materials: 'Wool',
      pricePerPair: 1.6,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'Low Cut',
      Materials: 'Wool',
      pricePerPair: 1.8,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'Low Cut',
      Materials: 'Wool',
      pricePerPair: 2,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'Low Cut',
      Materials: 'Wool',
      pricePerPair: 2.2,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'Quarter ',
      Materials: 'Wool',
      pricePerPair: 1.9,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'Quarter ',
      Materials: 'Wool',
      pricePerPair: 2.2,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'Quarter ',
      Materials: 'Wool',
      pricePerPair: 2.5,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'Quarter ',
      Materials: 'Wool',
      pricePerPair: 2.8,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'Crew',
      Materials: 'Wool',
      pricePerPair: 2.2,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'Crew',
      Materials: 'Wool',
      pricePerPair: 2.5,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'Crew',
      Materials: 'Wool',
      pricePerPair: 2.85,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'Crew',
      Materials: 'Wool',
      pricePerPair: 3.2,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'No Show',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.44,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'No Show',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.47,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'No Show',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.5,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'No Show',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.53,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'Low Cut',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.47,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'Low Cut',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.5,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'Low Cut',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.53,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'Low Cut',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.56,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'Quarter ',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.51,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'Quarter ',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.54,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'Quarter ',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.57,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'Quarter ',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.6,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'Crew',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.58,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'Crew',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.63,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'Crew',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.68,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'Crew',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.73,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'No Show',
      Materials: 'Nylon',
      pricePerPair: 0.44,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'No Show',
      Materials: 'Nylon',
      pricePerPair: 0.46,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'No Show',
      Materials: 'Nylon',
      pricePerPair: 0.48,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'No Show',
      Materials: 'Nylon',
      pricePerPair: 0.5,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'Low Cut',
      Materials: 'Nylon',
      pricePerPair: 0.49,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'Low Cut',
      Materials: 'Nylon',
      pricePerPair: 0.51,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'Low Cut',
      Materials: 'Nylon',
      pricePerPair: 0.53,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'Low Cut',
      Materials: 'Nylon',
      pricePerPair: 0.55,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'Quarter ',
      Materials: 'Nylon',
      pricePerPair: 0.52,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'Quarter ',
      Materials: 'Nylon',
      pricePerPair: 0.55,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'Quarter ',
      Materials: 'Nylon',
      pricePerPair: 0.58,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'Quarter ',
      Materials: 'Nylon',
      pricePerPair: 0.61,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'Youth',
      Silhouette: 'Crew',
      Materials: 'Nylon',
      pricePerPair: 0.6,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'M',
      Silhouette: 'Crew',
      Materials: 'Nylon',
      pricePerPair: 0.64,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'L',
      Silhouette: 'Crew',
      Materials: 'Nylon',
      pricePerPair: 0.68,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Everyday',
      Size: 'XL',
      Silhouette: 'Crew',
      Materials: 'Nylon',
      pricePerPair: 0.72,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
  ]

  const formalList = [
    {
      Category: 'Formal',
      Size: 'M',
      Silhouette: 'Crew',
      Materials: 'Cotton',
      pricePerPair: 0.72,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Formal',
      Size: 'L',
      Silhouette: 'Crew',
      Materials: 'Cotton',
      pricePerPair: 0.78,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Formal',
      Size: 'XL',
      Silhouette: 'Crew',
      Materials: 'Cotton',
      pricePerPair: 0.84,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Formal',
      Size: 'M',
      Silhouette: 'Crew',
      Materials: 'Polyester',
      pricePerPair: 0.64,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Formal',
      Size: 'L',
      Silhouette: 'Crew',
      Materials: 'Polyester',
      pricePerPair: 0.68,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Formal',
      Size: 'XL',
      Silhouette: 'Crew',
      Materials: 'Polyester',
      pricePerPair: 0.72,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Formal',
      Size: 'M',
      Silhouette: 'Crew',
      Materials: 'Wool',
      pricePerPair: 3.1,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Formal',
      Size: 'L',
      Silhouette: 'Crew',
      Materials: 'Wool',
      pricePerPair: 3.3,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Formal',
      Size: 'XL',
      Silhouette: 'Crew',
      Materials: 'Wool',
      pricePerPair: 3.5,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Formal',
      Size: 'M',
      Silhouette: 'Crew',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.74,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Formal',
      Size: 'L',
      Silhouette: 'Crew',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.8,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Formal',
      Size: 'XL',
      Silhouette: 'Crew',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.86,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Formal',
      Size: 'M',
      Silhouette: 'Crew',
      Materials: 'Nylon',
      pricePerPair: 0.74,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Formal',
      Size: 'L',
      Silhouette: 'Crew',
      Materials: 'Nylon',
      pricePerPair: 0.8,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Formal',
      Size: 'XL',
      Silhouette: 'Crew',
      Materials: 'Nylon',
      pricePerPair: 0.86,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
  ]

  const performanceList = [
    {
      Category: 'Performance',
      Size: 'M',
      Silhouette: 'Low Cut',
      Materials: 'Cotton',
      pricePerPair: 0.66,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'L',
      Silhouette: 'Low Cut',
      Materials: 'Cotton',
      pricePerPair: 0.72,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'XL',
      Silhouette: 'Low Cut',
      Materials: 'Cotton',
      pricePerPair: 0.78,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'M',
      Silhouette: 'Quarter ',
      Materials: 'Cotton',
      pricePerPair: 0.67,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'L',
      Silhouette: 'Quarter ',
      Materials: 'Cotton',
      pricePerPair: 0.73,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'XL',
      Silhouette: 'Quarter ',
      Materials: 'Cotton',
      pricePerPair: 0.79,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'M',
      Silhouette: 'Crew',
      Materials: 'Cotton',
      pricePerPair: 0.71,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'L',
      Silhouette: 'Crew',
      Materials: 'Cotton',
      pricePerPair: 0.77,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'XL',
      Silhouette: 'Crew',
      Materials: 'Cotton',
      pricePerPair: 0.83,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'M',
      Silhouette: 'Low Cut',
      Materials: 'Polyester',
      pricePerPair: 0.5,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'L',
      Silhouette: 'Low Cut',
      Materials: 'Polyester',
      pricePerPair: 0.53,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'XL',
      Silhouette: 'Low Cut',
      Materials: 'Polyester',
      pricePerPair: 0.56,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'M',
      Silhouette: 'Quarter ',
      Materials: 'Polyester',
      pricePerPair: 0.52,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'L',
      Silhouette: 'Quarter ',
      Materials: 'Polyester',
      pricePerPair: 0.55,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'XL',
      Silhouette: 'Quarter ',
      Materials: 'Polyester',
      pricePerPair: 0.58,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'M',
      Silhouette: 'Crew',
      Materials: 'Polyester',
      pricePerPair: 0.64,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'L',
      Silhouette: 'Crew',
      Materials: 'Polyester',
      pricePerPair: 0.7,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'XL',
      Silhouette: 'Crew',
      Materials: 'Polyester',
      pricePerPair: 0.76,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'M',
      Silhouette: 'Low Cut',
      Materials: 'Wool',
      pricePerPair: 1.85,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'L',
      Silhouette: 'Low Cut',
      Materials: 'Wool',
      pricePerPair: 2,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'XL',
      Silhouette: 'Low Cut',
      Materials: 'Wool',
      pricePerPair: 2.15,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'M',
      Silhouette: 'Quarter ',
      Materials: 'Wool',
      pricePerPair: 2.1,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'L',
      Silhouette: 'Quarter ',
      Materials: 'Wool',
      pricePerPair: 2.3,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'XL',
      Silhouette: 'Quarter ',
      Materials: 'Wool',
      pricePerPair: 2.5,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'M',
      Silhouette: 'Crew',
      Materials: 'Wool',
      pricePerPair: 2.5,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'L',
      Silhouette: 'Crew',
      Materials: 'Wool',
      pricePerPair: 2.75,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'XL',
      Silhouette: 'Crew',
      Materials: 'Wool',
      pricePerPair: 3,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'M',
      Silhouette: 'Low Cut',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.69,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'L',
      Silhouette: 'Low Cut',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.73,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'XL',
      Silhouette: 'Low Cut',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.77,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'M',
      Silhouette: 'Quarter ',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.71,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'L',
      Silhouette: 'Quarter ',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.75,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'XL',
      Silhouette: 'Quarter ',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.79,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'M',
      Silhouette: 'Crew',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.68,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'L',
      Silhouette: 'Crew',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.74,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Performance',
      Size: 'XL',
      Silhouette: 'Crew',
      Materials: 'Bamboo Fiber',
      pricePerPair: 0.8,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
  ]

  const medicalCompressionList = [
    {
      Category: 'Medical Compression',
      Size: 'M',
      Silhouette: 'Knee High',
      Materials: 'Cotton',
      pricePerPair: 1.12,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Medical Compression',
      Size: 'L',
      Silhouette: 'Knee High',
      Materials: 'Cotton',
      pricePerPair: 1.23,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Medical Compression',
      Size: 'XL',
      Silhouette: 'Knee High',
      Materials: 'Cotton',
      pricePerPair: 1.35,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Medical Compression',
      Size: 'M',
      Silhouette: 'Knee High',
      Materials: 'Polyester',
      pricePerPair: 1.02,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Medical Compression',
      Size: 'L',
      Silhouette: 'Knee High',
      Materials: 'Polyester',
      pricePerPair: 1.11,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Medical Compression',
      Size: 'XL',
      Silhouette: 'Knee High',
      Materials: 'Polyester',
      pricePerPair: 1.2,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Medical Compression',
      Size: 'M',
      Silhouette: 'Knee High',
      Materials: 'Wool',
      pricePerPair: 3.5,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Medical Compression',
      Size: 'L',
      Silhouette: 'Knee High',
      Materials: 'Wool',
      pricePerPair: 3.8,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Medical Compression',
      Size: 'XL',
      Silhouette: 'Knee High',
      Materials: 'Wool',
      pricePerPair: 4.1,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Medical Compression',
      Size: 'M',
      Silhouette: 'Knee High',
      Materials: 'Bamboo Fiber',
      pricePerPair: 1.14,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Medical Compression',
      Size: 'L',
      Silhouette: 'Knee High',
      Materials: 'Bamboo Fiber',
      pricePerPair: 1.25,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
    {
      Category: 'Medical Compression',
      Size: 'XL',
      Silhouette: 'Knee High',
      Materials: 'Bamboo Fiber',
      pricePerPair: 1.36,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
  ]

  const babyList = [
    {
      Category: 'Baby',
      Size: 'Baby',
      Silhouette: '/',
      Materials: '/',
      pricePerPair: 0.46,
      phase3: '10%',
      phase2: '20%',
      phase1: '50%',
    },
  ]

  const surchargeLessThan500 = 1.5
  const surchargeBetween500And999 = 1.2
  const surchargeOver1000 = 1.1

  const categoryTip = 'Please select category first'
  const materialTip = 'Please select material'
  const silhouetteTip = 'Please select silhouette'
  const sizeTip = 'Please select size'
  const quantityTip = 'Please input quantity'

  const setOpts = (data: any[], attr: string) => {
    const opt: string[] = []
    data.forEach((item) => {
      const val = item[attr]
      if (!opt.length || !opt.includes(val)) {
        opt.push(val)
      }
    })
    return opt
  }

  const formatNumber = (val: number) => {
    const numberStr = Math.abs(val).toString()
    if (numberStr.includes('.')) {
      const parts = numberStr.split('.')
      let integerPart = parts[0]
      const decimalPart = parts[1] || ''
      integerPart = integerPart.replace(/\B(?=(\d{3})+(?!\d))/g, ',')
      return `${integerPart}.${decimalPart}`
    }
    return numberStr.replace(/\B(?=(\d{3})+(?!\d))/g, ',')
  }

  return {
    titleTxt,

    Categories,
    everydayList,
    formalList,
    performanceList,
    medicalCompressionList,
    babyList,
    surchargeLessThan500,
    surchargeBetween500And999,
    surchargeOver1000,

    categoryTip,
    materialTip,
    silhouetteTip,
    sizeTip,
    quantityTip,

    setOpts,
    formatNumber,
  }
}
